### ISSUE TITLE
data source was added by config and cannot be modified using the UI

### ISSUE THREAD

**Issue by novohool** [deepflowio/deepflow-dashboards#147]
grafana报错
```
Provisioned data source
This data source was added by config and cannot be modified using the UI. Please contact your server admin to update this data source.
```

解决方案
不拷贝文件
```
conf/provisioning/datasources/deepflow-datasource.yaml
```

人工添加
```
DeepFlow
http://deepflow-server:20416
http://deepflow-app:20418


DeepFlow MySQL
deepflow-mysql:30130
deepflow
root
deepflow

DeepFlow ClickHouse
deepflow-clickhouse
9000
default

DeepFlow-Tempo
DeepFlow-Tempo
http://deepflow-server:20416


DeepFlow-Prometheus
DeepFlow-Prometheus
http://deepflow-server:20416/prom
```

**Comment by 1473371932** [comment]
能否说一下你想做什么呀？看起来你想通过 grafana ui 来更改我们默认的数据源，但这并不合理呀，因为我们的数据源都是配置好的，改了之后就不能用了呀

**Comment by novohool** [comment]
> 能否说一下你想做什么呀？看起来你想通过 grafana ui 来更改我们默认的数据源，但这并不合理呀，因为我们的数据源都是配置好的，改了之后就不能用了呀

我要用新版本的grafana，不用自带的。并不是要改你的数据源，如果只有这种方式的话，没法跟其他的平台公用一个grafana

**Comment by novohool** [comment]
> 能否说一下你想做什么呀？看起来你想通过 grafana ui 来更改我们默认的数据源，但这并不合理呀，因为我们的数据源都是配置好的，改了之后就不能用了呀

Query Timeout (seconds)  需要调大点

**Comment by 1473371932** [comment]
> > 能否说一下你想做什么呀？看起来你想通过 grafana ui 来更改我们默认的数据源，但这并不合理呀，因为我们的数据源都是配置好的，改了之后就不能用了呀
> 
> 我要用新版本的grafana，不用自带的。并不是要改你的数据源，如果只有这种方式的话，没法跟其他的平台公用一个grafana

抱歉，消息回复不及时
你们是用的自己的 Grafana 么？还是用的 Chart 包中的 Grafana 呢，看起来用的是 Chart 包中的 Grafana
如果如上所述，目前这种情况是合理的，你可以通过`kubectl describe deploy -n deepflow deepflow-grafana | grep Image;`查看我们是怎么处理的 Dashboard 和 插件，也是通过 init 镜像把内容 copy 进去的

**Comment by novohool** [comment]
> > > 能否说一下你想做什么呀？看起来你想通过 grafana ui 来更改我们默认的数据源，但这并不合理呀，因为我们的数据源都是配置好的，改了之后就不能用了呀
> > 
> > 
> > 我要用新版本的grafana，不用自带的。并不是要改你的数据源，如果只有这种方式的话，没法跟其他的平台公用一个grafana
> 
> 抱歉，消息回复不及时 你们是用的自己的 Grafana 么？还是用的 Chart 包中的 Grafana 呢，看起来用的是 Chart 包中的 Grafana 如果如上所述，目前这种情况是合理的，你可以通过`kubectl describe deploy -n deepflow deepflow-grafana | grep Image;`查看我们是怎么处理的 Dashboard 和 插件，也是通过 init 镜像把内容 copy 进去的

嗯，后面我打算全部使用mysql存储grafana，然后在sql上修改配置也可以。
